// automatically generated by the FlatBuffers compiler, do not modify
data class Date(
    val ts: ULong?,
)

data class Duration(
    val duration: ULong?,
)

data class Language(
    val code: String?,
)

data class URL(
    val url: String?,
)

data class RelativeLink(
    val link: String?,
)

data class MimeType(
    val encoding: String?,
)

data class Bool(
    val val: Boolean?,
)

data class String(
    val val: String?,
)

data class IntransitiveActivity(
)

data class Activity(
    val actor: ObjectOrLink,
    val instrument: ObjectOrLink,
    val origin: ObjectOrLink,
    val result: ObjectOrLink,
    val target: ObjectOrLink,
)

data class Object(
    val attachment: ObjectOrLink,
    val attributedTo: ObjectOrLink,
    val audience: ObjectOrLink,
    val bcc: ObjectOrLink,
    val bto: ObjectOrLink,
    val cc: ObjectOrLink,
    val context: ObjectOrLink,
    val generator: ObjectOrLink,
    val icon: ImageOrLink,
    val image: ImageOrLink,
    val inReplyTo: ObjectOrLink,
    val location: ObjectOrLink,
    val object: ObjectOrLink,
    val preview: ObjectOrLink,
    val replies: Collection,
    val tag: ObjectOrLink,
    val to: ObjectOrLink,
    val url: URLOrLink,
    val altitude: Float?,
    val content: String?,
    val name: String?,
    val duration: Duration,
    val mediaType: MimeType,
    val endTime: Date,
    val published: Date,
    val source_property: ObjectOrLink,
    val startTime: Date,
    val summary: String?,
    val updated: Date,
    val likes: MaybeOrderedCollection,
    val shares: MaybeOrderedCollection,
)

data class Link(
    val attributedTo: ObjectOrLink,
    val preview: ObjectOrLink,
    val name: String?,
    val height: UInt?,
    val href: URL,
    val hreflang: Language,
    val mediaType: MimeType,
    val rel: RelativeLink,
    val summary: String?,
    val width: UInt?,
)

data class Collection(
    val current: PageOrLink,
    val first: PageOrLink,
    val last: PageOrLink,
    val items: ObjectOrLink,
    val totalItems: UInt?,
)

data class OrderedCollection(
    val orderedItems: ObjectOrLink,
)

data class Question: IntransitiveActivity() (
    val oneOf: ObjectOrLink,
    val anyOf: ObjectOrLink,
    val closed: Various,
)

data class CollectionPage(
    val next: PageOrLink,
    val prev: PageOrLink,
    val partOf: CollectionOrLink,
)

data class Place(
    val accuracy: Float?,
    val latitude: Float?,
    val longitude: Float?,
    val radius: Float?,
    val units: StringOrURL,
)

data class Image(
    val height: UInt?,
    val width: UInt?,
)

data class OrderedCollectionPage(
    val startIndex: UInt?,
)

data class Relationship(
    val subject: ObjectOrLink,
    val relationship: Object,
)

data class Profile(
    val describes: Object,
)

data class Tombstone(
    val formerType: ObjectOrString,
    val deleted: Date,
)

data class Application: Object() (
    val inbox: OrderedCollection,
    val outbox: OrderedCollection,
    val following: MaybeOrderedCollection,
    val followers: MaybeOrderedCollection,
    val liked: MaybeOrderedCollection,
    val streams: MaybeOrderedCollection,
    val preferredUsername: String?,
)

data class Group: Object() (
    val inbox: OrderedCollection,
    val outbox: OrderedCollection,
    val following: MaybeOrderedCollection,
    val followers: MaybeOrderedCollection,
    val liked: MaybeOrderedCollection,
    val streams: MaybeOrderedCollection,
    val preferredUsername: String?,
)

data class Organization: Object() (
    val inbox: OrderedCollection,
    val outbox: OrderedCollection,
    val following: MaybeOrderedCollection,
    val followers: MaybeOrderedCollection,
    val liked: MaybeOrderedCollection,
    val streams: MaybeOrderedCollection,
    val preferredUsername: String?,
)

data class Person: Object() (
    val inbox: OrderedCollection,
    val outbox: OrderedCollection,
    val following: MaybeOrderedCollection,
    val followers: MaybeOrderedCollection,
    val liked: MaybeOrderedCollection,
    val streams: MaybeOrderedCollection,
    val preferredUsername: String?,
)

data class Service: Object() (
    val inbox: OrderedCollection,
    val outbox: OrderedCollection,
    val following: MaybeOrderedCollection,
    val followers: MaybeOrderedCollection,
    val liked: MaybeOrderedCollection,
    val streams: MaybeOrderedCollection,
    val preferredUsername: String?,
)

data class Accept: Activity() (
)

data class TentativeAccept: Activity() (
)

data class Add: Activity() (
)

data class Arrive: Activity() (
)

data class Create: Activity() (
)

data class Delete: Activity() (
)

data class Follow: Activity() (
)

data class Ignore: Activity() (
)

data class Join: Activity() (
)

data class Leave: Activity() (
)

data class Like: Activity() (
)

data class Offer: Activity() (
)

data class Invite: Activity() (
)

data class Reject: Activity() (
)

data class TentativeReject: Activity() (
)

data class Remove: Activity() (
)

data class Undo: Activity() (
)

data class Update: Activity() (
)

data class View: Activity() (
)

data class Listen: Activity() (
)

data class Read: Activity() (
)

data class Move: Activity() (
)

data class Travel: Activity() (
)

data class Announce: Activity() (
)

data class Block: Activity() (
)

data class Flag: Activity() (
)

data class Dislike: Activity() (
)

data class Question: Activity() (
)

sealed class PageOrLink {
    class CollectionPage : PageOrLink()
    class Link : PageOrLink()
}

sealed class ImageOrLink {
    class Image : ImageOrLink()
    class Link : ImageOrLink()
}

sealed class CollectionOrLink {
    class Link : CollectionOrLink()
    class Collection : CollectionOrLink()
}

sealed class ObjectOrLink {
    class Link : ObjectOrLink()
    class Object : ObjectOrLink()
}

sealed class Various {
    class Object : Various()
    class Link : Various()
    class Date : Various()
    class Bool : Various()
}

sealed class ObjectOrString {
    class Object : ObjectOrString()
    class String : ObjectOrString()
}

sealed class MaybeOrderedCollection {
    class OrderedCollection : MaybeOrderedCollection()
    class Collection : MaybeOrderedCollection()
}

sealed class URLOrLink {
    class URL : URLOrLink()
    class Link : URLOrLink()
}

sealed class StringOrURL {
    class String : StringOrURL()
    class URL : StringOrURL()
}

sealed class ActivityStream {
    class Accept : ActivityStream()
    class TentativeAccept : ActivityStream()
    class Add : ActivityStream()
    class Arrive : ActivityStream()
    class Create : ActivityStream()
    class Delete : ActivityStream()
    class Follow : ActivityStream()
    class Ignore : ActivityStream()
    class Join : ActivityStream()
    class Leave : ActivityStream()
    class Like : ActivityStream()
    class Offer : ActivityStream()
    class Invite : ActivityStream()
    class Reject : ActivityStream()
    class TentativeReject : ActivityStream()
    class Remove : ActivityStream()
    class Undo : ActivityStream()
    class Update : ActivityStream()
    class View : ActivityStream()
    class Listen : ActivityStream()
    class Read : ActivityStream()
    class Move : ActivityStream()
    class Travel : ActivityStream()
    class Announce : ActivityStream()
    class Block : ActivityStream()
    class Flag : ActivityStream()
    class Dislike : ActivityStream()
    class Question : ActivityStream()
}

sealed class Actor {
    class Application : Actor()
    class Group : Actor()
    class Organization : Actor()
    class Person : Actor()
    class Service : Actor()
}
